<?php

// DATABASE CREDENTIALS 
define('SERVER_NAME', '<PUT YOUR DATABASE SERVER IP/NAME HERE>');
define('DB_NAME', '<PUT YOUR DATABASE NAME HERE>');
define('DB_USER', '<PUT YOUR DATABASE USER NAME HERE');
define('DB_PASS', '<PUT YOUR DATABASE PASSWORD HERE');

//AUTHENTICATION CREDENTIALS
define('BASIC_AUTH_USER', '<PUT YOUR BASIC AUTH USERNAME HERE>');
define('BASIC_AUTH_PASS', '<PUT YOUR BASIC AUTH PASSWORD HERE');
